### ISSUE TITLE
Can't import a backup export after fresh install

### ISSUE THREAD

**Issue by lowe0292** [firebase/firebase-import#30]
I installed this from npm (node 6.11.2) and ran `firebase-import --database_url https://castle-scott-lowe.firebaseio.com/ --path / --json 2017-09-06T10-50-37Z_castle_data.json` to import a recent export, but got the following error:
```
Reading /Users/scott/Downloads/2017-09-06T10-50-37Z_castle_data.json... (may take a minute)
buffer.js:11
    super(arg1, arg2, arg3);
    ^

RangeError: Invalid typed array length
    at Buffer.Uint8Array (native)
    at FastBuffer (buffer.js:11:5)
    at createUnsafeBuffer (buffer.js:38:12)
    at allocate (buffer.js:181:12)
    at Function.Buffer.allocUnsafe (buffer.js:141:10)
    at tryCreateBuffer (fs.js:475:21)
    at Object.fs.readFileSync (fs.js:520:14)
    at Object.Module._extensions..json (module.js:585:20)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

**Comment by siege-nnn** [comment]
@lowe0292 hey, are you still having this issue? can you paste the json file?
