### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by orcunozbay** [firebase/firebase-import#38]
size += JSON.stringify(value).length;
                                 ^

TypeError: Cannot read property 'length' of undefined

**Comment by dougdot3** [comment]
Getting the same error.

`Preparing JSON for import... (may take a minute)
/usr/local/lib/node_modules/firebase-import/bin/firebase-import.js:199
    size += JSON.stringify(value).length;
                                 ^

TypeError: Cannot read property 'length' of undefined
    at chunkInternal (/usr/local/lib/node_modules/firebase-import/bin/firebase-import.js:199:34)
    at createChunks (/usr/local/lib/node_modules/firebase-import/bin/firebase-import.js:169:18)
    at Stream.<anonymous> (/usr/local/lib/node_modules/firebase-import/bin/firebase-import.js:147:18)
    at emitOne (events.js:101:20)
    at Stream.emit (events.js:188:7)
    at Parser.parser.onError (/usr/local/lib/node_modules/firebase-import/node_modules/JSONStream/index.js:140:12)
    at Parser.proto.charError (/usr/local/lib/node_modules/firebase-import/node_modules/jsonparse/jsonparse.js:90:8)
    at Parser.proto.write (/usr/local/lib/node_modules/firebase-import/node_modules/jsonparse/jsonparse.js:154:23)
    at Stream.<anonymous> (/usr/local/lib/node_modules/firebase-import/node_modules/JSONStream/index.js:21:12)
    at Stream.stream.write (/usr/local/lib/node_modules/firebase-import/node_modules/through/index.js:26:11)`

**Comment by siege-nnn** [comment]
@dougdot3 @orcunozbay try loading your file using the below.

What is the output?

$ cat test.js
var data = require('./testFile.json')
console.log(data.length)

$ node test.js
12054

**Comment by Shery11** [comment]
Same issue

**Comment by smacnabb3** [comment]
did anyone ever figure this out?

**Comment by oseiasgomes** [comment]
Mesmo Problema. Isso não funciona.
