### ISSUE TITLE
Import times out?

### ISSUE THREAD

**Issue by ReganBell** [firebase/firebase-import#8]
I consistently get the following error after trying to upload a JSON file that is ~40MB in size. Any ideas why? It always happens when the upload is 42% complete, and that portion of the JSON is successfully uploaded to Firebase.

FIREBASE INTERNAL ERROR: Server Error: ClientId[-----]:ErrorId[5]: Error on incoming message 
Importing [====================                             ] 42% (1610/3865)
/usr/local/lib/node_modules/firebase-import/node_modules/firebase/lib/firebase-node.js:44
function ac(a){try{a()}catch(b){setTimeout(function(){throw b;},Math.floor(0))
                                                            ^
AssertionError: false == true
    at onComplete (/usr/local/lib/node_modules/firebase-import/bin/firebase-import.js:222:7)
    at /usr/local/lib/node_modules/firebase-import/node_modules/firebase/lib/firebase-node.js:128:47
    at ac (/usr/local/lib/node_modules/firebase-import/node_modules/firebase/lib/firebase-node.js:44:20)
    at X (/usr/local/lib/node_modules/firebase-import/node_modules/firebase/lib/firebase-node.js:128:22)
    at /usr/local/lib/node_modules/firebase-import/node_modules/firebase/lib/firebase-node.js:121:291
    at /usr/local/lib/node_modules/firebase-import/node_modules/firebase/lib/firebase-node.js:85:276
    at md.h.bc (/usr/local/lib/node_modules/firebase-import/node_modules/firebase/lib/firebase-node.js:86:104)
    at ad.bc (/usr/local/lib/node_modules/firebase-import/node_modules/firebase/lib/firebase-node.js:77:364)
    at Q.Od (/usr/local/lib/node_modules/firebase-import/node_modules/firebase/lib/firebase-node.js:75:280)
    at Ec (/usr/local/lib/node_modules/firebase-i

**Comment by mikelehen** [comment]
Can you email me (michael@firebase.com) with the exact error message (including the ClientID) and the name of your Firebase?  We'll take a look.

**Comment by puf** [comment]
Cross-posted on http://stackoverflow.com/questions/30722127/firebase-import-timing-out
